### ISSUE TITLE
Upgrading to 2.0.1 causes an error

### ISSUE THREAD

**Issue by alexciciocupper** [agent-ly/nestjs-agenda#6]
Upgraded from 1.1.2 to 2.0.1 and getting this error
Did anything change with the decorators ? I'm not seeing anything in the readme.

Thanks !
```
TypeError: Cannot destructure property 'name' of 'this.metadataAcessor.getDefinitionOptions(...)' as it is undefined.
2022-06-17T06:20:13.289875054Z     at MapIterator.iteratee (/app/node_modules/@agent-ly/nestjs-agenda/lib/agenda.explorer.ts:42:21)
   at MapIterator.next (/app/node_modules/iterare/src/map.ts:9:39)
   at FilterIterator.next (/app/node_modules/iterare/src/filter.ts:11:34)
   at IteratorWithOperators.next (/app/node_modules/iterare/src/iterate.ts:19:28)
   at Function.from (<anonymous>)
   at IteratorWithOperators.toArray (/app/node_modules/iterare/src/iterate.ts:227:22)
   at MetadataScanner.scanFromPrototype (/app/node_modules/@nestjs/core/metadata-scanner.js:12:14)
   at /app/node_modules/@agent-ly/nestjs-agenda/lib/agenda.explorer.ts:35:30
   at Array.forEach (<anonymous>)
   at AgendaExplorer.explore (/app/node_modules/@agent-ly/nestjs-agenda/lib/agenda.explorer.ts:28:8)
```

**Comment by timofei-iatsenko** [comment]
Confirm, has the same

**Comment by devlzcode** [comment]
nothing changed on my end so the previous version works as intended. just had to do some black magic to merge changes and get versioning right. issue is likely a nestjs change
